name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build agent-ui library
        run: npx ng build agent-ui

      - name: Run unit tests
        run: npm test

      # Optional: build demo app
      - name: Build demo-agent
        run: npx ng build demo-agent

      # Optional: Serve app for E2E testing (requires Playwright/Cypress setup)
      # - name: Start dev server
      #   run: npx ng serve demo-agent & sleep 10
